name: 'Grafana Adaptive Metrics Auto-apply (Pull Recommendations)'
description: 'Pull your latest Adaptive Metrics recommendations.'
runs:
    using: 'docker'
    image: '../docker/Dockerfile'
    args:
      - pull
inputs:
  working-dir:
    default: './'
    description: 'The directory to place the recommendations in.'
