name: 'Grafana Adaptive Metrics Auto-apply (Apply Recommendations)'
description: 'Apply your Adaptive Metrics recommendations.'
runs:
    using: 'docker'
    image: '../docker/Dockerfile'
    args:
      - apply
inputs:
  working-dir:
    default: './'
    description: 'The directory to run the apply in.'
  dry-run:
    default: 'false'
    description: 'Whether to apply the recommendations or just print a summary of changes.'
outputs:
  changes-detected:
    description: 'Whether any changes were detected in the recommendations.'