name: 'Grafana Adaptive Metrics Auto-apply (Apply Recommendations)'
description: 'Apply your Adaptive Metrics recommendations.'
runs:
    using: 'docker'
    image: 'Dockerfile'
inputs:
  working-dir:
    default: './'
    description: 'The directory to run the apply in.'
  dry-run:
    default: 'false'
    description: 'Whether to apply the recommendations or just print tf plan output.'
  managed-by:
    default: 'gh-action-autoapply'
    description: 'The tag used to set the managed_by label on applied rules.'
