name: Clean up orphaned branches
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: grafana/shared-workflows/actions/cleanup-branches@36e5c2754eabcbb9c1201a7fc6b2bf2aa2deb7ab # cleanup-branches/v0.3.1
        with:
          dry-run: "false"

