name: Triggered apply of Adaptive Metrics recommendations

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'recommendations.json'
      - 'recommendations-*.json'
      - 'main.tf'

permissions:
  contents: write
  pull-requests: write

jobs:
  do-autoapply:
    uses: ./.github/workflows/apply_recommendations.yml
    with:
      grafana_am_api_url: ${{ vars.grafana_am_api_url }}
    secrets:
      grafana_am_api_key: ${{ secrets.grafana_am_api_key }}
