name: Scheduled refresh of Adaptive Metrics recommendations

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  do-autoapply:
    uses: ./.github/workflows/pull_recommendations.yml
    with:
      grafana_am_api_url: ${{ vars.grafana_am_api_url }}
    secrets:
      grafana_am_api_key: ${{ secrets.grafana_am_api_key }}
      automerge_pat: ${{ secrets.automerge_pat }}
