name: Pull Adaptive Metrics recommendations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1-5"
  workflow_call:
    inputs:
      grafana_am_api_url:
        description: "The URL of the Adaptive Metrics API."
        required: true
        type: string
      grafana_am_automerge_enabled:
        description: "Whether to enable auto-merge for the pull request."
        required: false
        default: false
        type: boolean
    secrets:
      grafana_am_api_key:
        description: "The API key for the Adaptive Metrics API."
        required: true

jobs:
  autoapply:
    runs-on: ubuntu-latest
    name: Pull the latest Adaptive Metrics recommendations
    permissions:
      contents: write
      pull-requests: write
    env:
      GRAFANA_AM_API_URL: ${{ vars.grafana_am_api_url }}
      GRAFANA_AM_API_KEY: ${{ secrets.grafana_am_api_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull recommendations
        uses: ./pull_recommendations
        id: pull_recommendations
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: Scheduled refresh of the latest recommendations.
          commit-message: Scheduled refresh of the latest recommendations.
          body: Scheduled refresh of the latest recommendations.
      - name: Enable pull request auto-merge
        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' && vars.grafana_am_automerge_enabled == 'true' }}
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}
