name: Pull Adaptive Metrics recommendations

on:
  workflow_call:
    inputs:
      grafana_am_api_url:
        required: true
        type: string
    secrets:
      grafana_am_api_key:
        required: true
      automerge_pat:

jobs:
  autoapply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GRAFANA_AM_API_URL: ${{ inputs.grafana_am_api_url }}
      GRAFANA_AM_API_KEY: ${{ secrets.grafana_am_api_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull recommendations
        uses: ./pull_recommendations
        id: pull_recommendations
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: Scheduled refresh of the latest recommendations.
          commit-message: Scheduled refresh of the latest recommendations.
          body: Scheduled refresh of the latest recommendations.
      - name: Enable pull request auto-merge
        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' && env.GH_TOKEN != '' }}
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.automerge_pat }}
